# Generated by Django 5.0.7 on 2024-07-23 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=30)),
                ('age', models.IntegerField(max_length=30)),
                ('address', models.TextField(max_length=30)),
            ],
            options={
                'db_table': 'emp',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField(max_length=30)),
                ('month', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=300)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_app.emp')),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
